name: study_hall
description: "A flashcard app for education"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.2
  firebase_ui_auth: ^1.16.1
  google_sign_in: ^6.3.0
  firebase_ui_oauth_google: ^1.4.1
  cloud_firestore: 5.6.5
  firebase_vertexai: ^0.2.0
  matrix4_transform: ^4.0.1
  go_router: ^14.2.0
  table_calendar: ^3.1.3
  graphic: ^2.5.1
  image_picker: ^1.0.4
  shared_preferences: ^2.3.0
  flutter_tts: ^4.2.2
  google_mlkit_text_recognition: ^0.15.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/src/assets/study_hall_icon.png