# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Flutter CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - uses: actions/checkout@v4

      # Step 2: Set up Flutter SDK
      # Note: This uses a specific stable version of Flutter. Adjust the version as needed.
      # See documentation: https://github.com/subosito/flutter-action
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.0' # Specify a stable version (update to match your local version)
          channel: 'stable'        # Use stable channel for consistency
          cache: true              # Cache Flutter SDK for faster runs

      # Step 3: Verify Flutter installation
      - name: Check Flutter Version
        run: flutter --version

      # Step 4: Install dependencies
      - name: Install Dependencies
        run: flutter pub get

      # Uncomment to enforce Dart code formatting (Flutter includes Dart formatter)
      # - name: Verify Formatting
      #   run: flutter format --set-exit-if-changed .

      # Step 5: Analyze project source
      # Pass '--fatal-infos' for stricter analysis if desired
      - name: Analyze Project Source
        run: flutter analyze

      # Step 6: Run tests
      # Assumes tests are in test/ and use package:test (included in flutter_test)
      - name: Run Tests
        run: flutter test

      # Optional: Build the web app (uncomment if deploying to GitHub Pages)
      # - name: Build Web App
      #   run: flutter build web --release

      # Optional: Deploy to GitHub Pages (uncomment if needed)
      # - name: Deploy to GitHub Pages
      #   uses: peaceiris/actions-gh-pages@v3
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     publish_dir: build/web
